### PR TITLE
Docker support & fix terraform template

### LINKED ISSUE #49: Deploy Failed in latestcognito_iam_roles.tf
The following line has an extra ",' and causes terraform to fail from a fresh git.

https://github.com/Coalfire-Research/npk/blob/8ed3b47ad778bbbc2806789a2fbc0c2b7adf4b28/terraform/cognito_iam_roles.tf#L39

### PR DESCRIPTION
**Pull request by AlphaGit**
Added a dockerfile that builds a docker image to use npk. This provides two benefits.

1. If CoalfireLabs decides to publish and maintain the npk image, then users can just run npk by using a single command line in docker.

2. If CoalfireLabs does not publish a docker image, users can still use this dockerfile to build the container themselves.

This prevents everyone from dealing with multiple terraform, python, pip and node versions that do not quite work together.

Pending to be done:

- Add ARGs, ENVs or a startup script (á la MySQL) so that the container can setup the aws credential profile when running and does not need to be a manual process.
- Add ARG, ENVs or a startup script (á la MySQL) so that the container can setup the /npk/terraform/npk-settings.json file and does not need to be a manual process.
- After these are done, we can remove `nano` (or any text editor) being installed, making the image smaller and faster to create.

This change also fixes the error in the `terraform/cognito_iam_roles.tf` template, which basically just had an extra comma. Fixes #49.

### CODE REVIEW

**Comment by mubix** [comment]
This one also fixes the comma which will conflict with #61 if it's merged first

**Comment by AlphaGit** [comment]
@mubix That is correct, but the conflict resolution is so simple that adjusting will be a breeze. If this one gets merged first, #61 would not be needed and can be just discarded.

**Comment by c6fc** [comment]
This is a great idea. I'll test it soon and merge it if everything looks good.

**Comment by robellegate** [comment]
I think this is a great idea! @AlphaGit, if I can provide any help with the pending changes for config via ARGs/ENVs/startup script, please let me know.

**Comment by AlphaGit** [comment]
@robellegate No worries, I had completely forgotten about this. Since I initially wrote this my expertise with Docker has grown a lot so I think I should be able to take care of it.

**Comment by AlphaGit** [comment]
(Closing in favour of https://github.com/c6fc/npk/pull/5)

**Pull request closed without merging**
